### PR TITLE
Refs #17. move notebooks to subdirs

### PR DESCRIPTION
**Pull request by yxqd**
* Most notebooks were now moved into /notebooks/
* Jean's "(FULL)" notebooks are in /solutions/

### CODE REVIEW

**Review by ricleal — APPROVED** [review]
I'm OK with that. But I have splitted my notebook in 2 with the same nomenclature as Jean. You may have a conflict merging that.

**Comment by yxqd** [comment]
@ricleal did you push your changes to master yet? If not, maybe you can wait for this PR to be merged? I pulled the most recent changes from master before I created this PR and did not see the split.

**Comment by ricleal** [comment]
@yxqd I pushed :(
I just worked on my 2 files... that was the reason.

**Comment by yxqd** [comment]
OK. let me try to merge the master

**Comment by yxqd** [comment]
@ricleal I merged yours. I did not remove your original notebook that is not yet splitted. Please check and delete it if you like.

**Pull request merged**
